[gcp]
project_id = "your-gcp-project-id"
project_number = "your-gcp-project-number"

[stripe]
public_key = "your-stripe-public-key"
secret_key = "your-stripe-secret-key"
webhook_secret = "your-stripe-webhook-secret"

[google]
client_id = "your-google-client-id"
client_secret = "your-google-client-secret"
redirect_uri = "http://localhost:8501"

[vertex_ai]
model_name = "gemini-1.5-flash"
location = "us-central1" 